### ISSUE TITLE
FilesManager.UploadAsync automatic refresh token cause Exception

### ISSUE THREAD

**Issue by mkiosugadaikichi** [box/box-windows-sdk-v2#352] opened 2017-07-03 04:15 UTC
I found automatic refresh token while upload cause Exception.

`System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a closed Stream.`

I guess
at first attempt, stream is available.
first attempt fails because of expired access token.
automatic refresh token take place.
at second attempt, stream was already read to end and disposed.

**Comment by coolboy** [comment] 2017-07-05 20:14
HI @mkiosugadaikichi ,

I suspect this is because the underlaying http connection closed due to keep-alive setting, not really related to the token.

So after the failed second attempt, as long as your token is valid, a retry should re-establish the connection and everything should work from there.

**Comment by mkiosugadaikichi** [comment] 2017-07-06 02:24
Thanks for reply.
Stack trace shows MemoryStream throws Exception.

```
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.get_Position()
   at System.Net.Http.StreamToStreamCopy.StartAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Box.V2.Managers.BoxFilesManager.<UploadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxBatch.Program.<mainAsync>d__1.MoveNext() in C:\Users\04173\documents\visual studio 2015\Projects\BoxSDKErrorCase\BoxBatch\Program.cs:line 50
```

```C#
using Box.V2;
using Box.V2.Auth;
using Box.V2.Config;
using Box.V2.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace BoxBatch
{
    class Program
    {
        static void Main(string[] args)
        {
            mainAsync().Wait();
        }

        static private async Task mainAsync()
        {
            var client_id = ConfigurationManager.AppSettings["client_id"];
            var client_secret = ConfigurationManager.AppSettings["client_secret"];
            var redirect_uri = ConfigurationManager.AppSettings["redirect_uri"];
            var tokenFile = ConfigurationManager.AppSettings["tokenFile"];

            var config = new BoxConfig(client_id, client_secret, new Uri(redirect_uri));
            var client = new BoxClient(config, loadSession(tokenFile));

            client.Auth.SessionAuthenticated += (s, e) => saveSession(e.Session, tokenFile);

            var req = new BoxFileRequest()
            {
                Name = "samplefile.txt",
                Parent = new BoxRequestEntity() { Id = "0" }
            };

            try
            {
                using (var stream = new MemoryStream(Encoding.UTF8.GetBytes("sample content")))
                {
                    await client.FilesManager.UploadAsync(req, stream);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        static private void saveSession(OAuthSession session, string filename)
        {
            var json = JsonConvert.SerializeObject(session, Formatting.Indented);

            using (var tw = File.CreateText(filename))
            {
                tw.WriteLine(json);
            }
        }

        static OAuthSession loadSession(string filename)
        {
            string json;

            using (var sr = new StreamReader(filename))
            {
                json = sr.ReadToEnd();
            }

            var session = JsonConvert.DeserializeObject<OAuthSession>(json);

            // always pass invalid access_token to force refresh
            return new OAuthSession("invalid token", session.RefreshToken, session.ExpiresIn, session.TokenType);
        }
    }
}
```

token file is
```json
{
  "access_token": "<your access token>",
  "refresh_token": "<your refresh token>",
  "expires_in": 4039,
  "token_type": "bearer",
  "restricted_to": [],
  "AuthVersion": 1
}
```

**Comment by mattwiller** [comment] 2018-03-20 04:43
@mkiosugadaikichi Thanks for the detailed reproduction case — I was able to debug the issue and figure out what's going on here.

This issue actually __does__ have to do directly with the tokens expiring — since the .NET SDK does not preemptively refresh tokens, it sends the entire request before it knows that your tokens are expired (which it "discovers" when it gets a 401 response from the API).  Since it already sent the entire upload request, the Stream containing the file contents has already been read to the end — when we retry the request, it does not have any more bytes and the retry fails.  The fix for this is going to be a bit involved, since in general Streams can only be read one time (not all Streams can be reset or re-seeked to the beginning).  We'll probably need to implement preemptive token refreshing, which is probably the best solution, but may take some time to implement correctly.  For the time being, I would recommend working around this issue by manually retrying your request when you see this error — recreate the file contents stream and make the request again since the client will have updated tokens by the time you get the exception.

**Comment by ChristianGalla** [comment] 2020-11-23 14:44
@lgvw3 if you or someone else still is interested in a workaround until this is fixed:
Simply retry all calls of BoxClient.FilesManager.UploadAsync, BoxClient.FilesManager.UploadNewVersionAsync, BoxClient.FilesManager.UploadUsingSessionAsync and BoxClient.FilesManager.UploadNewVersionUsingSessionAsync.

For example:
```
public async Task<BoxFile> UploadAsync(Stream stream, string fileName, string parentFolderId, int retryDelayInMs, int maxRetries, byte[] hash = null, IEnumerable<string> retFields = null)
{
	int retries = 0;
	while (true)
	{
		try
		{
			MemoryStream localStream = new MemoryStream();
			stream.Seek(0, SeekOrigin.Begin);
			stream.CopyTo(localStream);
			var fileUploadRequest = new BoxFileRequest
			{
				Name = fileName,
				Parent = new BoxRequestEntity
				{
					Id = parentFolderId
				}
			};
			var file = await BoxClient.FilesManager.UploadAsync(fileRequest: fileUploadRequest, stream: localStream, contentMD5: hash, fields: retFields);
			return file;
		}
		catch (Exception ex)
		{
			if (retries < maxRetries) {
				throw;
			}
			Thread.Sleep(retryDelayInMs);
			retries++;
			continue;
		}
	}
}
```

@mattwiller Token expiration is not the only possible error. For example there may be a network issue after a token expiration has been checked. If not all streams can be read multiple times, I suggest to create a memory copy inside the SDK before the upload is started.

**Comment by lukedubber** [comment] 2021-10-08 22:53
This is still an issue... Any update?

**Closed** 2021-10-12 09:13 UTC
Labels: bug
