### ISSUE TITLE
C# Code failing while Retrieving Admin Token 

### ISSUE THREAD

**Issue by Pavan0255** [box/box-windows-sdk-v2#576] opened 2019-07-17 16:51 UTC
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Iam trying to export documents from .Net based application to BOX. For some reason its failing 
while retrieving the admin token(var adminToken = boxJWT.AdminToken();). The same code if i convert into .exe file its working.Not sure what is going wrong when i call the DLL to export the documents to Box. Can you guys give some pointers?

### Versions Used
.Net Version: .Net Framework 4.5.2
BOX Version: 3.18.0
Microsoft IndentityModel Token Version:5.3.0
System IdentityModel Tokens Jwt Version: 5.3.0
Newtonsoft.Json version : 10.0.3

### Error Message, Including Stack Trace
The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception.
Exit getFnmBoxClientObj    at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
   at System.IdentityModel.Tokens.Jwt.JwtPayload.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtPayload.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.get_EncodedPayload()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at Box.V2.JWTAuth.BoxJWTAuth.ConstructJWTAssertion(String sub, String boxSubType, Nullable`1 nowOverride)
   at Box.V2.JWTAuth.BoxJWTAuth.GetToken(String subType, String subId)
   at Box.V2.JWTAuth.BoxJWTAuth.AdminToken()
   at TestBoxConnection.TestBox.getFnmBoxClientObj()

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment] 2019-07-17 20:55
Hey @Pavan0255,

Can you please shoot us over your enterprise ID to ccheng@box.com?

We will do our best to look into this

**Comment by Pavan0255** [comment] 2019-07-22 14:44
I emailed you the details. Please let me know if you need anything.

**Comment by carycheng** [comment] 2019-07-26 01:20
Hello @Pavan0255,

After looking at your issue it's difficult to troubleshoot on our end. The call you are trying to make seems to stemming from before a single API call has been made and somewhere in the set up.

It seems from the issue description that this is an environment issue as the portion of the code that calls to retrieve an admin token has been untouched for some time now.

Unfortunately, at this time we can't be sure what is the root cause of the issue you are encountering. If you come across a specific error within the Windows SDK we will be happy to take this on.

Thank you for your patience

**Comment by Pavan0255** [comment] 2019-07-31 13:53
here is the inner exception iam getting

Exit getFnmBoxClientObj System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=*********************'
   at System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Pavan0255** [comment] 2019-07-31 13:54
here is the inner exception iam getting
Exit getFnmBoxClientObj System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad****************'
or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad****************'
   at System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by mattwiller** [comment] 2019-07-31 18:09
@Pavan0255 Unfortunately, this does not appear to be an error in the SDK.  The SDK depends on Newtonsoft.Json 10.x, so if your project is looking for 9.x that's probably something from your project.  You may need to update your dependency version or [redirect the assembly binding](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions) in order to make your project work with the SDK.

**Comment by PJSimon** [comment] 2020-01-07 05:14
Hi @Pavan0255, How did you make out with this issue?  I'm going to close this issue for now, but if you're still having issues, please feel free to re-open it!

**Closed by PJSimon** 2020-01-07 05:14 UTC
Labels: question
