### ISSUE TITLE
Getting the "current" stream position via EnterpriseEventsAsync

### ISSUE THREAD

**Issue by Dave-Lowndes** [box/box-windows-sdk-v2#371] opened 2017-08-01 11:16 UTC
Now that v3 has fixed the internationalization issue with the datetime parameter passed to EnterpriseEventsAsync I'm reworking our piece of code to get the current stream position:
				

		DateTime? dt = DateTime.Now;
		var boxEvents = await cli.EventsManager.EnterpriseEventsAsync( 500, null, null, dt );
		string streamPosition = boxEvents.NextStreamPosition;

Unfortunately, unless there are some events returned, NextStreamPosition is set to "0", which isn't what's I would expect.

**Comment by Dave-Lowndes** [comment] 2017-08-01 12:35
Oddly, if I pass "1" for the initial stream position, then events are returned, while passing null, "", or "0" doesn't return any.

**Comment by coolboy** [comment] 2017-08-01 21:30
Hi @Dave-Lowndes 

This is by design of this API (EnterpriseEvents), if there is no events in the response, there won't be any usable NextStreamPosition returned.

One thing I recommend to do is to poll this API every a few minutes, to see if there are new events available

**Comment by Dave-Lowndes** [comment] 2017-08-01 21:59
Hi @coolboy,

Then how (from an initialisation point of view), do we get a "current" stream position?

Background...

Until now, on system initialisation we've been looping, getting all events (without specifying the time parameter as it didn't work) to get a current stream position (the point at which we received no further events). The drawback with that is that once there's a massive number of events in the system, this took many minutes to complete - but at the end we had a current stream position which we could subsequently use to poll periodically to get subsequent events.

I'd assumed that by specifying the time (as shown in my code snippet), that would have returned the current latest stream position.

How do we get the current stream position without taking many minutes?

Do you have any comment on the different behaviour when I specify "1" as the initial stream position?

**Comment by mattwiller** [comment] 2018-03-16 04:33
@Dave-Lowndes Can you give me a bit more detail about what you mean when you say that the time parameter didn't work for you?  I tried the following code and it worked fine:

```c#
DateTime startTime = DateTime.Now.AddDays(-1);
var events = await client.EventsManager.EnterpriseEventsAsync(500, createdAfter: startTime);
// events contains events from roughly the last day, and a valid `NextStreamPosition` value
```

Using something like that should allow you to fairly quickly get a current stream position without needing to go through too many events to get to the current one.

**Comment by Dave-Lowndes** [comment] 2018-03-16 08:05
@mattwiller Your code example isn't what I showed. We wanted to get the current stream position at the time when our service started. Your example is probably fudging things by getting the method to return some results. I bet that if there weren't any events from yesterday, the issue will be the same.

**Comment by mattwiller** [comment] 2018-03-17 03:30
@Dave-Lowndes Sure, I understand that — the example was just intended to illustrate something that did work, since I wasn't sure what exactly you meant by "the time parameter [...] didn't work".  You were asking "How do we get the current stream position without taking many minutes?" — one solution is to try to set a `createdAfter` value of the current time and request any events starting from right now.  If that returns 0 events (and thus no `next_stream_position` value), then that would mean that there are no events yet and you should be able to repeat that call over and over until you __do__ get some events, which should be after the time when you started calling.  Those will then give a stream position, which you can use to get more events — if that call returns no events and no `next_stream_position`, just repeat it until you get something.  Here's an example that should do roughly what you want:

```c#
string streamPosition = null;
DateTime startTime = DateTime.Now;

while (true)
{
    if (streamPosition == null)
    {
        BoxEventCollection<BoxEnterpriseEvent> events = await client.EventsManager.EnterpriseEventsAsync(createdAfter: startTime);
        if (events.Entries.Count > 0)
        {
            // process events
        }
        if (events.NextStreamPosition != "0")
        {
            streamPosition = events.NextStreamPosition;
        }
    }
    else
    {
        BoxEventCollection<BoxEnterpriseEvent> events = await client.EventsManager.EnterpriseEventsAsync(streamPosition: streamPosition);
        if (events.Entries.Count > 0)
        {
            // process events
        }
        if (events.NextStreamPosition != "0")
        {
            streamPosition = events.NextStreamPosition;
        }
    }
}
```

**Comment by Dave-Lowndes** [comment] 2018-03-19 10:44
@mattwiller regarding your original comment "_Can you give me a bit more detail about what you mean when you say that the time parameter didn't work for you?_". There was an internationalization issue - I mentioned it the initial post "_Now that v3 has fixed the internationalization issue with the datetime parameter passed to EnterpriseEventsAsync_".

Regarding your last follow-up post, that may work, we're no longer working on the project, we went with passing "1" as a bodge.

**Comment by mattwiller** [comment] 2018-03-19 17:50
@Dave-Lowndes Ah, okay — thanks for clarifying!  I'm going to close this issue since it seems like you have something working, but feel free to re-open or file a new issue if something comes up!

**Closed by mattwiller** 2018-03-19 17:50 UTC
Labels: bug, enhancement
