### ISSUE TITLE
.Net Box V2 2.0.1 SDK getInformationAsync does not refresh token

### ISSUE THREAD

**Issue by pktruong** [box/box-windows-sdk-v2#110] opened 2015-09-15 00:23 UTC
Hi,
When calling getInformationAsync, if the access token is expired, BoxSessionInvalidatedException is thrown.  We have been assuming that SDK code will automatic refresh.

Is there a fix for this.
Thanks,

**Comment by brianytang** [comment] 2015-09-18 19:17
Can you provide more information on how you are instantiating the BoxClient and how you are calling the method after the access token is expired? 

Is this in a client application or in a server context? The default implementation of the token refresh handles it in memory, so if the code is reinitialized, the developer is responsible for persisting the tokens somehow

**Comment by pktruong** [comment] 2015-09-21 19:40
Hi,
I think after investigating, the problem is in our code.  But We are confused by how the refresh token works.

let say we have multiple app running all use the same account (same client id and secret)

They all start with the same accesstoken1 and refreshtoken1

At 1 hour mark, app call BOX SDK uploadasync which refreshes to get  accesstoken2 and refreshtoken2.

However, the other app are running the time, also cause a refresh and gets refreshtoken2 accesstoken 2.

They all get different accesstokens and continue to work fine.  How can this be possible?
I thought after the first refresh, the old accesstoken1 and refreshtoken1 are obsolete and cannot be used to refresh anymore

Please help.
Thanks,
Phong

**Comment by cburnette** [comment] 2015-09-21 20:24
hmm, that is interesting.  You should be seeing the second refresh attempt fail.

Chad

**Comment by brianytang** [comment] 2015-09-22 01:42
* You mentioned you have multiple apps sharing the same client id/secret:
  * While you can run multiple different apps with the same client id/secret -- if the apps are meant to serve different purposes, they should be created as separate apps within box with different client ids/secrets. This is recommended but not required
  * Can you provide more details on what these different apps are and how they interact with one another?
* As for the apps starting with the same access token and refresh token -- this should be avoided as this will likely cause one app to not refresh properly.
  * The behavior of refresh is as follows: Upon refreshing, the tokens used for the refresh will be invalidated. Issuing additional refresh requests with the same token will continue to return the same new set of access/refresh token. 

Can you provide more details on how the refresh is being called? Is this consistently reproducible?

**Comment by pktruong** [comment] 2015-09-22 06:05
Hi,
1/ The app simply call uploadasync to upload files.
2/ There are no communication between them 
3/ We dont call refresh.  This is automatic refresh from the uploadasync.  We know its refreshed because we print out the tokens before and after.

4/ You statement is not clear:
 you said " the tokens used for the refresh will be invalidated." .  

However, then you said " Issuing additional refresh requests with the same token will continue to return the same new set of access/refresh token. "

so is it invalidated ? or it can still be used to refresh token.  Note: Refresh tokens are being inside uploadasync

5/ How would you suggest we handle the tokens in this env?   How do we generate different clientID and Secret from 1 account ?  Can we do that automatically.

THanks,
Phong

**Comment by doncung** [comment] 2015-09-22 06:21
Hi Phong,

What Brian means is that if you refresh with refresh token 1, you will get
the same access and refresh token 2 regardless how many times you call it
probably up to an hour. Once the new access token 2 is used though, refresh
token 1 will stop working.
It is thus possible for both apps to refresh successfully as long as they
both refresh before using access token 2. We don't recommend this though as
such behavior will be unpredictable.
As for question 5, you can use the same client id and secret, but you
should login separately to generate a different access and refresh token.
(Use the login webpage). That will not conflict.

Don

**Comment by pktruong** [comment] 2015-09-22 17:06
Hi,
Thanks for the clarification.  I understand now.  

But now what should I do.  I found this thead:
https://github.com/box/box-windows-sdk-v2/issues/31
which had exactly the same problem as mine.  And we were advised to implement serialization of our keystore but with the condition that we can turn off SDK automatic refresh. Can we do that now?

Or is there a new interface for keystore serialization  already?

Thanks,
Phong

**Comment by brianytang** [comment] 2015-09-23 16:51
The interface mentioned in the thread does not appear to be implemented yet.

If the access/refresh tokens are being shared across multiple apps, you will need to override the RefreshAccessTokenAsync virtual method with an implementation that suits your needs

**Comment by Rod-Sychev** [comment] 2015-09-23 21:42
Hello Brian,

We've got pretty much the same issue where several instances of the same web app are deployed and could you the same pair of tokens simultaneosly and eventually tokens are getting expired despite of several workarounds we were trying to put in to overcome this issue.
I believe it's about time you told us how this is supposed to work really as none of your advices seem to have any effect on the token refresh logic as eventually  they would become obsolete anyways. 
Our clients are super unhappy about this and I honestly don't know what to tell them.
Hopefully you can shed some light on this and help other developers too.

**Comment by brianytang** [comment] 2015-09-24 03:43
Hi Rodion,

I'm sorry to hear you're still having issues, but running multiple applications with the same access/refresh tokens is not a configuration that we can support in our SDK out of the box. The issue here is that the tokens must be locked on to be kept in sync, and as a SDK, we do not have access to a persistence layer to accomplish this. This is why the recommendation is to override the existing refresh logic with one that incorporates your respective token persistence layer. 

The original thread compared the ease of other services that had tokens that never expired -- this was the case in our original v1 API. However, we moved away from this in favor of short-lived tokens as security is a top priority at Box. Unfortunately, because of the nature of expiring tokens, I do not have any better suggestions.

**Comment by pktruong** [comment] 2015-09-24 05:53
Hi Brian,
So if I dont want autorefresh happens, what exactly should I do in the function? return an error? throw an exception?   I need to do something that when i am executing an BOx SDK API such as uploadasync to recognize that this is my autorefresh returning so that i can skip the error?

Thanks,
Phong

PS. and why cant you simply provide an option to turn it off as asked a year ago in thread 31#

**Comment by brianytang** [comment] 2015-09-24 17:40
If you would like to disable auto refresh and only receive notifications when a token expires you can do this by extending the AuthRepository object and overriding the RefreshAccessTokenAsync method and calling OnSessionInvalidated(). Then when creating the BoxClient, pass in your instance of AuthRepository and attach an event handler on the session invalidated event.

I do not believe the referenced post requested the ability to turn off auto refresh. They did mention that it may be better to call a handler on refresh instead of a method within the AuthRepository. I agree that the refresh logic may be better served in a call back, but the work to make this change has not been prioritized. Regardless of changing the logic to a callback, there will still need to be custom code to keep the tokens in sync -- this is also mentioned by the poster.

**Comment by pktruong** [comment] 2015-09-24 17:52
Hi,
If I dont cause an error/exception in the RefreshAccessTokenAsync method, then will BOX SDK , upon successful return from this method, attempt to retry the operation?  This is what I dont want happen sine we know its going to fail again,

**Comment by brianytang** [comment] 2015-09-24 20:21
Yes you can throw a BoxSessionInvalidatedException to short circuit the logic

This is what the existing logic does when a token refresh fails. see: 
https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Auth/AuthRepository.cs#L170

**Comment by pktruong** [comment] 2015-09-24 21:12
1 more question:
Can we do this:
    When my RefreshAccessTokenAsync is called, 
      1/ we will lock keystore of the  tokens.  
       2/ Then see if there are a new tokens, (ie, some other app already refreshed),
             a/ grab them, and set them
             b/ return ok so BOX SDK retry the operation 
      3/ if there are not new tokens (ie, this is the first time we hit the expired tokens)
             a/ call the base  RefreshAccessTokenAsync to perform refresh
             b/ store the new tokens in the keystore
             c/ unlock the keystore
             d/ return so BOX SDK continue to retry the operation


can you help to see if step 3a is ok?  

Thanks,
Phong

**Comment by brianytang** [comment] 2015-09-25 22:32
Yes, that sounds like a good approach.

for 3a, you likely don't need to call the base.RefreshAccessTokenAsync and can call ExchangeRefreshTokens instead. That method makes the actual refresh API call.

**Comment by pktruong** [comment] 2015-10-06 05:04
Hi,
Turns out that we cannot easily override RefreshAccessTokenAsync  .  In order to do this we have to subclass  AuthRepository.  Bit this new class cannot be used to create the BoxClient.  We will have to copy the code in the constructor of the BoxClient and create several more objects such as Http..... before we can create the BoxClient object we use. 

This quite polluted. it is so easy for BOX SDK to provide an option to turn off autorefresh.   But yet BOX support refused to do so.  

In anycase, we are at the end of our release so we have to live with it.  Can you advise exactly how can we subclass and override this function please

Thanks,
Phong

**Comment by brianytang** [comment] 2015-10-06 05:17
Subclassing is the only way to override the method. This is currently how it is done in our Windows app: 

```C#
IBoxConfig _config = new BoxConfig(Constants.ConsumerKey, Constants.ClientSecret, new Uri(Constants.RedirectUri));
_config.UserAgent = UserAgentHelper.BuildUserAgent();
_config.DeviceId = DeviceInfoHelper.UniqueDeviceId();
_config.DeviceName = DeviceInfoHelper.UniqueDeviceName();
var handler = new HttpRequestHandler();
var converter = new BoxJsonConverter();
var service = new BoxService(handler);
var auth = new BoxCrossProccessAuthRepository(_config, service, converter, _settingsService, session);
var client = new BoxClient(_config, converter, handler, service, auth);
```

**Comment by Rod-Sychev** [comment] 2015-10-26 21:59
Brian,

Locking the keystore is not an option for our distributed architecture.
Would the newly introduced JWT Auth mechanism resolve our issues here at all?

Thanks.

**Comment by brianytang** [comment] 2015-11-04 20:58
I don't know exactly what your use case is, but there are no refresh tokens in the JWT auth.

Just know that you'll have to stand up your own JWT service to handle auth for your users. Perhaps look through the documentation to see if it fits your needs:
https://box-content.readme.io/docs/box-platform

**Comment by Rod-Sychev** [comment] 2015-12-03 21:20
I don't think this model would suit us.

**Comment by coolboy** [comment] 2017-09-15 17:44
closing due to last activity is more than 30 days

**Closed by coolboy** 2017-09-15 17:44 UTC
