### ISSUE TITLE
Using the box windows sdk in powershell take 2

### ISSUE THREAD

**Issue by whiggs** [box/box-windows-sdk-v2#454] opened 2018-03-08 15:23 UTC
This issue is being opened in reference to issue #426 .  Since it appears that nobody wants to go back and look at old posts, allow me to create a new one which will pick up where #426 left off:
@carycheng @mattwiller So the official decision is that it is a broken dependency issue on Microsoft's end? Then I would like to present the following scenario and see if that still holds true. Below you will see a screenshot of the dependencies for the box.v2 assembly as displayed on nuget.org (which you are probably already very familiar with):
![image](https://user-images.githubusercontent.com/11139575/37158961-a6e3875e-22ba-11e8-9201-06096dfbf9e3.png)

Notice how the System.IdentityModel.Tokens.Jwt dependency can be greater than or equal to 5.1.4. If what you have previously claimed as a broken dependency specification and that assemblies, in general, should be able to use an assembly version greater than the version listed when the dependency specifies greater than or equal to said version, then, by that logic, I should be able to use the latest version of the System.IdentityModel.Tokens.Jwt assembly (in which the Newtonsoft.Json assembly dependency version has been updated to version 10, thus eliminating the need for the Newtonsoft.Json version 9.0.0 assembly altogether, which was the idea) instead of the version which nuget downloads when running the "nuget install box.v2" command. However, this is not what happens when System.IdentityModel.Tokens.Jwt (and its dependencies) are replaced by with the most up to date version of the assembly and its dependencies (5.2.1):
![image](https://user-images.githubusercontent.com/11139575/37158958-a1783b2a-22ba-11e8-9711-ff0b43eeb206.png)

Care to comment and explain how exactly this is Microsoft's problem again? The issue is currently being discussed on their end too, but the information you previously provided about assembly dependencies does not hold up, and it is starting to seem much more like Box's problem again, not Microsofts.....

**Comment by mattwiller** [comment] 2018-03-08 18:36
Closing this as a duplicate of #426

**Closed by mattwiller** 2018-03-08 18:36 UTC
